### ISSUE TITLE
slight changes to translate tool

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#20]
1. Change "verbiage" (db table name) to role-pattern or role-pattern-linkage or something more specific
2. When creating a new verbiage entry, don't show ones (in pulldown) for which one already exists. I created inadvertently an empty string corresponding to rebel-activist road trip.
3. I'll check my developer reset issue with another browser. It didn't seem to work with Safari. (but I'll recheck that also)

**Comment by smrose** [comment]
1. Changing the name of a table would be a gigantic amount of work. I'd do it for something user-facing, but for a tool that will be used by a handful of people I resist. Users will never see the name of the table.
3. If you try to create a verbiage string for a combination of role and pattern that already exists, it won't be allowed. Populating the drop-down menu for pattern with only those patterns for which a role-pattern pair already exists could be done, but it would take a lot of Javascript to do it because that set of patterns depends upon which role has been selected. And it's not clear why it would be useful. Whoever is creating verbiage strings knows which ones exist and presumably has developed text for new ones.

You say that you created an empty string for Rebel/Activist Road Trip. What does that have to do with this issue?

The developer toolbar isn't shown on the translate tool, so that's out of scope of this issue.
