### ISSUE TITLE
make existing patterns show up in the developers bar?

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#32]
It would make debugging the texts for the last page if the existing patterns were shown in the "Select pattern1" etc. buttons. I could flip one or two patterns and see the new results. You could leave the role blank if that worked better. How easy would it be to make that change? 

<img width="1054" alt="Screenshot 2024-11-13 at 4 39 19 PM" src="https://github.com/user-attachments/assets/af0a928f-3d50-4395-9d71-def442f85308">

**Comment by smrose** [comment]
I'm pretty sure that what you are asking for is that instead of resetting the role and pattern selections after they are selected and the location updated, they remain set where they were before the location is updated. I think that should be easy enough, but let me know if you meant something else.

**Comment by smrose** [comment]
The new design for the developer bar replaces the "reset" button with a "go" button. If there is a valid set of roles and patterns selected, the "go" button becomes active. Pressing it changes the location, which used to happen without a button press.

When the page is reloaded, the query parameters are used to set the values in the popup menus. I think that was what you were asking for.
