### ISSUE TITLE
Issues with verbiage and translate tool

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#33]
For three of the role types there are five entries for the concluding page in the verbiage translate section. There are only four for reformer and I'm not sure which one is missing. I think it's the default verbiage when nothing is selected, but if that's the case, I can't add it, because the "default" (no pattern) isn't an option on the add new string.

**Comment by smrose** [comment]
I demur from the claim that there are only 4 entries for reformer (role == 4). The translate tool doesn't directly label the rows in the form, but it does add a 'title' attribute to each static string on the left. To see that, mouse over. There are the expected five entries for role 4: 3 specific patterns, 1 labeled "n/a", and 1 labled "none matched." But there is no text for 4_10 - pattern 10 is Grassroots Public Policy Development. You can enter it in the form. I tested that and it works.

I agree that there is no means to add a default string for a role. At one level, that's a bug in the tool. But since all the roles already have default strings, and because it would be an error to add a second one, it's not something that could ever be used to create a string, and I think I won't bother to add it.

Using the 'title' attribute to show the translator the context of a string is very cheap, but it's awkward because you can only see one at a time. I'm going to work on fixing that.

BTW, an issue title such as "I keep getting myself confused" isn't useful. Please make the effort to think about how somebody browsing issues needs to be able to tell what they are about from the issue titles and assign a title that is useful for that.
